language: node_js
env:
  - CI=true CI_ENGINE=travis # 写成多行会触发 matrix 的功能
sudo: false

node_js:
  - "node"  # latest stable Node.js release
  - "iojs"  # latest stable io.js release
  - "6"     # latest 6.x release
  - "5"
  - "4"
  - "0.12"

before_script:
  - node --version
  - npm --version
script:
  - npm run lint
  - npm test -- --check-coverage
after_script:
  - npm run coverage

notifications:
  email:
    - qiuzhongleiabc@126.com

